name: Download and process CSV Files

on:
  push:
    branches:
      - trunk
  schedule:
    - cron: '10 14 * * WED'

jobs:
  process-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download c19 infection data zip file
      run: wget -O downloads/c19.zip https://sseruminstitut.maps.arcgis.com/sharing/rest/content/items/67a8aedc7ff9466e8920951540c2097f/data

    - name: Download inluenza infection data zip file
      run: wget -O downloads/infl.zip https://sseruminstitut.maps.arcgis.com/sharing/rest/content/items/e23ed8a4d8f843259f0f9f6c2e084e16/data

    - name: Download RSV infection data zip file
      run: wget -O downloads/rsv.zip https://sseruminstitut.maps.arcgis.com/sharing/rest/content/items/add51841daa34019953ef73b4a7ed4c8/data

    - name: Unzip c19 file
      run: unzip -o downloads/c19.zip -d unzipped_data

    - name: Unzip influenza file
      run: unzip -o downloads/infl.zip -d unzipped_data

    - name: Unzip rsv file
      run: unzip -o downloads/rsv.zip -d unzipped_data

    - name: Change encoding from ISO_8859-15 to UTF-8
      run: |
        mkdir -p utf8_data
        for file in unzipped_data/*.csv; do
          iconv -f ISO_8859-15 -t UTF-8 "$file" > "utf8_data/$(basename "$file")"
        done

    - name: Copy to docs, commit and push changes
      run: |
        git config --global user.name 'Steen Hulthin Rasmussen'
        git config --global user.email 'steenhulthin@gmail.com'
        cp -r utf8_data/* ./docs
        git add .
        git commit -m 'Downloaded and updated c19 data'
        git push
